---
title: "Presented at Law of Giving Symposium, University of Windsor"
date: "2024-06-26"
categories: [talk]
---

I presented "Algorithms in Personal Crowdfunding: Evidence from GoFundMe Healthcare Campaigns" at the Law of Giving Symposium, hosted by the University of Windsor's Faculty of Law.

> **Abstract.** This paper identifies personal crowdfunding as an important case of the intersection of algorithmic decision-making and the politics of social welfare. Crowdfunding is a significant means by which individuals and families in low, middle, and high-income countries fund various welfare needs, most notably healthcare. While proponents describe it as a democratic practice, occurring on platforms that act as neutral arbiters of deservingness, scholars draw attention to the low success rates and highly unequal outcomes associated with crowdfunding. This paper discusses algorithms' role in shaping crowdfunding outcomes and, by extension, access to social welfare resources in areas neglected by the welfare state. Based on analyses of cross-national data on crowdfunding campaigns from the platform GoFundMe, we present evidence that crowdfunding use is shaped by social policy contexts and subject to fundraising disparities based on age and race and ethnicity that are in part attributable to the platform's algorithmic selection of featured campaigns. This research underscores the pitfalls of market-based solutions to welfare needs and raises concerns about fairness, discrimination, and human rights at this novel intersection of charity and profit.
