---
title: "Presented at ASA Annual Meeting, Montreal"
date: "2024-08-10"
categories: [talk]
---

I presented "A Formal Model of Social Influence," with Vanina Leschziner, Peter Marbach, and Daniel Silver, at the American Sociological Association Annual Meeting in Montreal, Canada.

::: {.abstract}
This paper develops a formal model of social influence as a sociological analogue to the informational dimension of prices in the economy. The model elaborates the role of influence in communicating information about the collective structure of a group's interests, broadly analogously to the role of prices in communicating the state of a market (Banfield 2017; Mayhew 2023). In addition, we specify the role of social support as a mechanism for exercising influence, and the effects of influence on the overall social welfare of the group. In our formal model, influence represents a sociological form of information, in which a public good – reliable knowledge about where a community's interests lie – arises from individuals' personal pursuit of interesting content and social support. Our findings identify a remarkable duality: micro-sociological conditions where, as actors pursue their own interests, they generate a macro-sociological structure whose influential actors represent the interests of the community as a whole.
:::
