---
title: "Presented at Eastern Sociological Society Conference, Boston"
date: "2025-03-07"
categories: [talk]
---

I presented "Territorial Identification in Contemporary Europe" at the Eastern Sociological Society Conference in Boston, MA.

::: {.abstract}
What is the relationship between global and local identification, and how is it linked to political conflict? These questions are central to scholarship on contemporary electoral politics, which has linked the radical right's rise to a new dimension of political conflict that sets culturally liberal, globally minded voters against conservative, locally oriented ones. This hypothesized cleavage, variously described as universalist–particularist, cosmopolitan–parochial, and globalist–nationalist, implies that collective identification is polarized along a global–local axis and that these differences drive political mobilization. Yet little is known about how territorial identities at different scales compete with or reinforce each other, let alone how their configurations connect to political preferences. Moreover, sociological theories of collective identification challenge the view that global identification occurs at the expense of local identification and vice versa, raising fundamental questions about the divisions structuring contemporary political competition. This study investigates patterns of multiple collective identification and their relation to electoral politics using latent class analysis and survey data from Europe. It finds that a subset of European countries can be characterized by a division between particularistic and expansive territorial identities, although there is overall less identity-based polarization than cleavage-based theories suggest. At the same time, identification patterns are associated with distinct sociodemographic profiles, and they divide parts of the electorate along the hypothesized cultural division demarcated by radical-right and new left parties.
:::
